assoc .mp3=mp3file
assoc .elf=elffile
assoc .epl=eplfile
assoc .ogg=oggfile
assoc .opus=opusfile
assoc .mod=modfile
assoc .xm=xmfile
assoc .s3m=s3mfile
assoc .it=itfile
assoc .669=f669file
assoc .wav=wavfile
assoc .flac=flacfile
assoc .alac=alacfile
assoc .wma=wmafile
assoc .fsb=fsbfile
assoc .asf=asffile
assoc .vag=vagfile
assoc .dls=dlsfile
assoc .asx=asxfile
assoc .raw=rawfile
assoc .iff=ifffile

ftype mp3file="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype elffile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype eplfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype oggfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype opusfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype modfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype xmfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype s3mfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype itfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype f669file="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype wavfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype flacfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype alacfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype wmafile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype fsbfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype asffile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype vagfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype dlsfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype asxfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype rawfile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"
ftype ifffile="C:\Program Files\elpAudio\elpAudio.exe" "%%1"

